version: '3.9'

services:

  app:
    container_name: sanic_container
    build:
      context: .
    env_file:
      - .env-docker
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db

  db:
    container_name: postgres_container
    image: postgres
    env_file:
      - .env-docker
    ports:
      - '5435:5432'
    restart: always