version: '3.9'

services:

  backend:
    container_name: back_container
    build:
      context: .
    env_file:
      - .env-docker
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db

  frontend:
    container_name: front_container
    build:
      context: ./frontend
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - backend

  db:
    container_name: postgres_container
    image: postgres
    env_file:
      - .env-docker
    ports:
      - '5432:5432'
    restart: always